spring:
  datasource:
    url: jdbc:h2:mem:testdb_${random.uuid};MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트마다 DB 새로 생성/삭제
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true   # 통계 활성화 (선택)

  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz0123456789
    access-token-validity-seconds: 100000000
    refresh-token-validity-seconds: 1000000000

  redis:
    enabled: false

  kafka:
    bootstrap-servers: dummy:9092

  elasticsearch:
    uris: http://localhost:9200

  rabbitmq:
    host: localhost
    port: 5672
