spring:
  application:
    name: auction

  config:
    import: optional:application-secret.yml

  jwt:
    secret-key: ${jwt.secret-key}
    access-token-validity-seconds: ${jwt.access-token-validity-seconds}
    refresh-token-validity-seconds: ${jwt.refresh-token-validity-seconds}